### ISSUE TITLE
Crash on load (1.14 using fabric-loader-0.4.7+build.147-1.14.1+build.4)

### ISSUE THREAD

**Issue by SDUBZ** [Juuxel/Crafty#5]
rabric: fabric-loader-0.4.7+build.147-1.14.1+build.4
minecraft: 1.14.1
crash:

Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
 at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
 at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
 at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
 Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: crafty requires {fabric @ [>=0.2.7]})
 at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
 at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:483)
 at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
 ... 2 more
 Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
 at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
 at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
 at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
 at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
 at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
 ... 4 more

**Comment by Juuxel** [comment]
Same issue as Juuxel/Adorn#10.
